spring:
  application:
     name: web-service
server:
  port: 8090
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5
security:
  basic:
    enabled: false
