spring:
  application:
     name: competency-subject-service

server:
  port: 8010
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5

security:
  basic:
    enabled: false