spring:
  application:
     name: user-service

server:
  port: 8030
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5

security:
  basic:
    enabled: false