spring:
  application:
     name: user-service
  jpa:
      hibernate:
          ddl-auto: create
  datasource:
      url: jdbc:mysql://localhost/distlearning
      username: root
      password: root


server:
  port: 8030
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5

security:
  basic:
    enabled: false